package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/monetarium/monetarium-node/rpcclient"
)

// nodeProc is the node monvark started and owns.
type nodeProc struct {
	cmd *exec.Cmd
	rpc *rpcclient.Client

	// exited is closed once the node process has been reaped.  It is the only
	// liveness signal available: ProcessState stays nil until Wait returns, so
	// checking it directly would be dead code.
	exited chan struct{}
}

// hasExited reports whether the node process has already terminated.  Once it
// returns true, cmd.ProcessState is safe to read.
func (n *nodeProc) hasExited() bool {
	select {
	case <-n.exited:
		return true
	default:
		return false
	}
}

// freeAddr binds an ephemeral loopback port, returns the host:port the OS
// assigned, and releases it.  There is a small window between the release and
// the node's own bind in which another process could take it; it is local,
// brief, and the standard way to do this.  The node failing to bind is a clear
// startup error, not a silent misbehaviour.
func freeAddr() (string, error) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return "", err
	}
	defer ln.Close()
	return ln.Addr().String(), nil
}

// portFree reports whether hostport can be bound right now.
func portFree(hostport string) bool {
	ln, err := net.Listen("tcp", hostport)
	if err != nil {
		return false
	}
	ln.Close()
	return true
}

// randomCredential returns 32 bytes of hex from crypto/rand.
func randomCredential() (string, error) {
	var b [32]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(b[:]), nil
}

// mondConf renders the node's configuration.  It carries the credentials and
// nothing else: keeping rpcpass out of the command line keeps it out of `ps`,
// while the payout address stays on the command line because a miningaddr in a
// file would be appended to, not overridden by, the one we pass.
func mondConf(rpcUser, rpcPass, rpcListen, rpcCert, rpcKey string) string {
	return fmt.Sprintf(""+
		"; Generated by monvark.  Rewritten on every start; edits are lost.\n"+
		"; The payout address is deliberately not here -- it is passed on the\n"+
		"; node's command line, because the node picks at random among its\n"+
		"; configured mining addresses and a second one would take a share.\n"+
		"rpcuser=%s\n"+
		"rpcpass=%s\n"+
		"rpclisten=%s\n"+
		"rpccert=%s\n"+
		"rpckey=%s\n",
		rpcUser, rpcPass, rpcListen, rpcCert, rpcKey)
}

// checkMondConf validates an existing node configuration before it is replaced.
// Overwriting would be safe, since our values win, but silently repairing a
// file somebody edited hides the event worth reporting.
func checkMondConf(path string) error {
	body, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}

	if err := checkPerms(path); err != nil {
		return err
	}

	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, ";") || strings.HasPrefix(line, "#") {
			continue
		}
		key, _, _ := strings.Cut(line, "=")
		switch strings.TrimSpace(key) {
		case "miningaddr", "generate":
			return fmt.Errorf("%s contains %q, which monvark never writes; "+
				"it would redirect the block reward.  Delete the file and "+
				"restart, or investigate who added it", path, key)
		}
	}
	return nil
}

// mondArgs builds the node's command line.  --generate is never passed: the
// node's default is off, and a node with CPU mining enabled refuses getwork.
func mondArgs(cfg *config, confPath, appData, addr string, p2pBusy bool) []string {
	args := []string{
		"--configfile=" + confPath,
		"--appdata=" + appData,
		"--miningaddr=" + addr,
	}
	if p2pBusy {
		// Another node already holds the default P2P port.  Without this the
		// child dies at startup: the node skips a P2P address it cannot bind
		// but fails outright when none succeeded.  On an ephemeral port it
		// still dials out, syncs, validates and relays -- it just cannot
		// accept inbound peers, which is already true of any rig behind NAT.
		args = append(args, "--listen=:0")
	}
	switch {
	case cfg.TestNet:
		args = append(args, "--testnet")
	case cfg.SimNet:
		args = append(args, "--simnet")
	}
	return args
}

// mondPath resolves the node binary.  It sits beside monvark in the archive,
// which is the only layout the release produces; override is the development
// path, where monvark is a `go build` output with no node next to it.
func mondPath(exeDir, override string) (string, error) {
	if override != "" {
		if _, err := os.Stat(override); err != nil {
			return "", fmt.Errorf("--mond %s: %w", override, err)
		}
		return override, nil
	}

	name := "mond"
	if runtime.GOOS == "windows" {
		name = "mond.exe"
	}
	path := filepath.Join(exeDir, name)
	if _, err := os.Stat(path); err != nil {
		return "", fmt.Errorf("the node binary %q was not found in %s; it "+
			"ships in the same archive as monvark, or pass --mond with its "+
			"path", name, exeDir)
	}
	return path, nil
}

// nodeStart configures and starts the node, and returns it with an RPC client
// connected to it.
func nodeStart(ctx context.Context, cfg *config, addr string) (*nodeProc, error) {
	exe, err := os.Executable()
	if err != nil {
		return nil, err
	}
	bin, err := mondPath(filepath.Dir(exe), cfg.Mond)
	if err != nil {
		return nil, err
	}

	confPath := filepath.Join(minerHomeDir, "mond.conf")
	if err := checkMondConf(confPath); err != nil {
		return nil, err
	}

	rpcListen, err := freeAddr()
	if err != nil {
		return nil, err
	}

	rpcUser, err := randomCredential()
	if err != nil {
		return nil, err
	}
	rpcPass, err := randomCredential()
	if err != nil {
		return nil, err
	}

	certPath := filepath.Join(minerHomeDir, "rpc.cert")
	keyPath := filepath.Join(minerHomeDir, "rpc.key")
	conf := mondConf(rpcUser, rpcPass, rpcListen, certPath, keyPath)
	if err := os.WriteFile(confPath, []byte(conf), 0600); err != nil {
		return nil, err
	}

	// The default P2P port belongs to whoever took it first.  We coexist with
	// an existing node rather than fighting it for the port or killing it.
	p2pDefault := net.JoinHostPort("", chainParams.DefaultPort)
	p2pBusy := !portFree(p2pDefault)
	if p2pBusy {
		mainLog.Warnf("P2P port %s is already in use, most likely by another "+
			"node; starting ours on an ephemeral port.  It will sync and "+
			"relay normally but cannot accept inbound peers.",
			chainParams.DefaultPort)
	}

	appData := filepath.Join(minerHomeDir, "node")
	args := mondArgs(cfg, confPath, appData, addr, p2pBusy)

	// exec.Command, not exec.CommandContext: CommandContext installs
	// Process.Kill as the context's cancel action, and ctx is the one Ctrl+C
	// cancels -- that would SIGKILL the node the instant the user interrupts,
	// before Stop() below could ask it to shut down gracefully.
	cmd := exec.Command(bin, args...)
	// Inherit stderr so startup failures are visible.  The node's own logs go
	// to appData/logs as normal.
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("failed to start %s: %w", bin, err)
	}

	n := &nodeProc{cmd: cmd, exited: make(chan struct{})}
	go func() {
		n.cmd.Wait()
		close(n.exited)
	}()
	mainLog.Infof("Started the node on %s", rpcListen)

	// The miner connects to the node monvark just started, so tell the rest of
	// the program where it is and how to authenticate to it.
	cfg.RPCServer = rpcListen
	cfg.RPCCert = certPath
	cfg.RPCUser = rpcUser
	cfg.RPCPassword = rpcPass

	n.rpc, err = n.connect(ctx, cfg)
	if err != nil {
		n.Stop()
		return nil, err
	}
	return n, nil
}

// connect waits for the node's RPC server to come up.  It retries because the
// node needs a moment to start and to generate its certificate, which does not
// exist at all on a first run.
func (n *nodeProc) connect(ctx context.Context, cfg *config) (*rpcclient.Client, error) {
	// A dcrd-family node opens its block database and initialises the chain
	// before it starts the RPC listener, which on a synced chain -- especially
	// after an unclean shutdown -- can take much longer than a few seconds.
	const timeout = 5 * time.Minute
	const logEvery = 15 * time.Second

	start := time.Now()
	deadline := start.Add(timeout)
	nextLog := start.Add(logEvery)
	var lastErr error
	for time.Now().Before(deadline) {
		if n.hasExited() {
			return nil, fmt.Errorf("the node exited during startup: %v",
				n.cmd.ProcessState)
		}

		certs, err := os.ReadFile(cfg.RPCCert)
		if err != nil {
			lastErr = err
		} else {
			client, err := rpcclient.New(&rpcclient.ConnConfig{
				Host:         cfg.RPCServer,
				User:         cfg.RPCUser,
				Pass:         cfg.RPCPassword,
				Certificates: certs,
				HTTPPostMode: true,
			}, nil)
			if err == nil {
				if _, err = client.GetBlockChainInfo(ctx); err == nil {
					return client, nil
				}
				client.Shutdown()
			}
			lastErr = err
		}

		// A long wait can otherwise look indistinguishable from a hang.
		if now := time.Now(); !now.Before(nextLog) {
			mainLog.Infof("Still waiting for the node's RPC server to come "+
				"up (%v so far)...", now.Sub(start).Round(time.Second))
			nextLog = now.Add(logEvery)
		}

		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(250 * time.Millisecond):
		}
	}
	return nil, fmt.Errorf("the node's RPC server did not come up within %v: %w",
		timeout, lastErr)
}

// Stop shuts the node down.  When an RPC client exists it uses the node's own
// stop RPC rather than a signal: os.Interrupt cannot be delivered through
// Process.Signal on Windows, and the Kill that would remain there risks the
// node's database.  This is one code path on every platform.
func (n *nodeProc) Stop() {
	wait := 30 * time.Second
	switch {
	case n.rpc != nil:
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		if _, err := n.rpc.RawRequest(ctx, "stop", nil); err != nil {
			mainLog.Warnf("Failed to ask the node to stop: %v", err)
		}
		cancel()
		n.rpc.Shutdown()
	case n.cmd != nil && n.cmd.Process != nil:
		// connect never got far enough to hand back a client -- it failed, or
		// the user interrupted the run during the node's startup window -- so
		// nothing was ever asked to stop.  Ask now by signal rather than
		// sitting through the full wait below for a shutdown nobody
		// requested.  os.Interrupt cannot be delivered through Process.Signal
		// on Windows, so there we just fall through to the shorter wait.
		if runtime.GOOS != "windows" {
			if err := n.cmd.Process.Signal(os.Interrupt); err != nil {
				mainLog.Warnf("Failed to interrupt the node: %v", err)
			}
		}
		wait = 5 * time.Second
	}

	if n.cmd == nil || n.cmd.Process == nil {
		return
	}

	select {
	case <-n.exited:
		mainLog.Info("The node shut down.")
	case <-time.After(wait):
		mainLog.Warn("The node did not shut down in time; killing it.")
		n.cmd.Process.Kill()
		<-n.exited
	}
}

// WaitSynced blocks until the node has caught up with the network.  Mining does
// not start before this returns.
func (n *nodeProc) WaitSynced(ctx context.Context) error {
	const poll = 2 * time.Second

	for {
		if n.hasExited() {
			return fmt.Errorf("the node exited while syncing: %v",
				n.cmd.ProcessState)
		}

		info, err := n.rpc.GetBlockChainInfo(ctx)
		if err != nil {
			return fmt.Errorf("unable to read the node's chain state: %w", err)
		}

		// The gate is the boolean, never blocks >= headers: on a clean machine
		// both are 0 before any header arrives, which reads as synced and
		// mines at height 1.
		if !info.InitialBlockDownload {
			mainLog.Infof("Synced at height %d.", info.Blocks)
			return nil
		}

		// The peer count is not decoration.  InitialBlockDownload is
		// !chain.IsCurrent(), and IsCurrent never becomes true without peers,
		// so a machine that cannot reach the network would otherwise sit at
		// 0.0% forever with nothing to explain why.
		peers, err := n.rpc.GetConnectionCount(ctx)
		if err != nil {
			peers = 0
		}
		mainLog.Infof("Syncing %5.1f%%  %d/%d blocks  %d peers",
			info.VerificationProgress*100, info.Blocks, info.Headers, peers)

		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(poll):
		}
	}
}
